spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/dvdrental"
    username: postgres
    password: root
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/dvdrental
    username: postgres
    password: root

server:
  undertow:
    worker-threads: 3
    io-threads: 3